### ISSUE TITLE
Error on multipart break

### ISSUE THREAD

**Issue by Stuff-Stuffs** [AlexIIL/LibMultiPart#11]
If a MultipartContainer has multiple pieces and one gets broken sometime (not sure what causes it) this error will be thrown
```
[00:53:57] [Server thread/INFO]: [STDERR]: alexiil.mc.lib.net.InvalidInputDataException: The client is aware of 1 parts, but the server has sent data for the 1 part!
[00:53:57] [Server thread/INFO]: [STDERR]: 	at alexiil.mc.lib.multipart.impl.PartContainer$1.readContext(PartContainer.java:129)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at alexiil.mc.lib.multipart.impl.PartContainer$1.readContext(PartContainer.java:103)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at alexiil.mc.lib.net.ParentNetIdDuel.readContext(ParentNetIdDuel.java:58)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at alexiil.mc.lib.net.NetIdTyped.receive(NetIdTyped.java:29)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at alexiil.mc.lib.net.InternalMsgUtil.onReceive(InternalMsgUtil.java:127)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at alexiil.mc.lib.net.BufferedConnection.onReceiveRawData(BufferedConnection.java:120)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at alexiil.mc.lib.net.impl.CoreMinecraftNetUtil.lambda$onServerReceivePacket$6(CoreMinecraftNetUtil.java:177)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.ServerTask.run(ServerTask.java:17)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:136)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:22)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:109)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:719)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:713)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:119)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:699)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:654)
[00:53:57] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by AlexIIL** [comment]
What were you doing when this was thrown? Does this happen with a lot of mods, or just a single one? Also, what versions of the mods were you using?

**Comment by Stuff-Stuffs** [comment]
[This](https://github.com/Stuff-Stuffs/Multipart-test) repo has a demo.
Just fabric and LibMultipart and its dependencies.
`fabric_version=0.4.25+build.282-1.15
minecraft_version=1.15.1
yarn_mappings=1.15.1+build.1
loader_version=0.7.2+build.175
alexiil.mc.lib:libmultipart-all:0.3.3`

**Comment by AlexIIL** [comment]
Ok, thanks, I've reproduced it and now I'll try to work out what's going on from that.causing that.
