### ISSUE TITLE
microblock crash/invisible

### ISSUE THREAD

**Issue by Skywrath-Mage** [AlexIIL/LibMultiPart#21]
Hello,
I have some issue with my server that use this library for simplepipes.

after an update of a mod linked to the maps and the restart of the server, the microblocks were no longer visible and if you try to go over where one of them was used you have these problems:

- on the server logs it shows that I am teleported.
```
[13:57:38] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 81 -167)->(-396 81 -167)
[13:57:38] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 81 -167)->(-396 81 -167)
[13:57:38] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 81 -167)->(-396 81 -167)
[13:57:39] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 81 -167)->(-396 81 -167)
[13:57:39] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 81 -167)->(-396 81 -167)
[13:57:39] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 81 -167)->(-396 81 -167)
[13:57:44] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:44] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:44] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:44] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:44] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:45] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:45] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:45] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:45] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:45] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:45] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:45] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:45] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:45] [Server thread/INFO]: request teleport Matt96 ResourceKey[minecraft:dimension / minecraft:overworld] (-396 80 -182)->(-396 80 -182)
[13:57:55] [Server thread/INFO]: Matt96 lost connection: Disconnected
[13:57:55] [Server thread/INFO]: Matt96 left the game
```
- if I try to break a block the client will crash
```
13:57:54] [Voxelmap LiveMap Calculation Thread/INFO]: [STDOUT]: image was null
[13:57:54] [Voxelmap LiveMap Calculation Thread/INFO]: [STDOUT]: image was null
[13:57:54] [Voxelmap LiveMap Calculation Thread/INFO]: [STDOUT]: image was null
[13:57:54] [Voxelmap LiveMap Calculation Thread/INFO]: [STDOUT]: image was null
[13:57:54] [Voxelmap LiveMap Calculation Thread/INFO]: [STDOUT]: image was null
[13:57:55] [main/INFO]: [STDERR]: alexiil.mc.lib.net.InvalidInputDataException: Packet failed to read correctly!

Packet: NetIdSignalK <AbstractPart> '.block_entity.libmultipart:container.container.holder.spawn_break_particles'
Payload Length: 7
Reader Index: 7. (Marked by '#')
Error: The client is aware of 1 parts, but the server has sent data for the 2 part!
Raw Bytes:
+---------
| 8b 43 d0 00 b7 41 01#                                       |  C   A 
+---------
WARNING: No type information found!
  Add '-Dlibnetworkstack.debug=true' to your VM arguments
  to record type information on packet read&write.
  Alternatively you can change 'debug' or 'debug.record_types' to true
  in the config file: C:\_gdl\instances\MekaCraft\config\libnetworkstack.txt


[13:57:55] [main/INFO]: [STDERR]: 	at alexiil.mc.lib.net.InternalMsgUtil.onReceive(InternalMsgUtil.java:383)
[13:57:55] [main/INFO]: [STDERR]: 	at alexiil.mc.lib.net.BufferedConnection.onReceiveRawData(BufferedConnection.java:126)
[13:57:55] [main/INFO]: [STDERR]: 	at alexiil.mc.lib.net.impl.CoreMinecraftNetUtil.lambda$onClientReceivePacket$5(CoreMinecraftNetUtil.java:146)
[13:57:55] [main/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:144)
[13:57:55] [main/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[13:57:55] [main/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:118)
[13:57:55] [main/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:103)
[13:57:55] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:988)
[13:57:55] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:654)
[13:57:55] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[13:57:55] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:57:55] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:57:55] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:57:55] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:57:55] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[13:57:55] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[13:57:55] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[13:57:55] [main/INFO]: [STDERR]: Caused by: alexiil.mc.lib.net.InvalidInputDataException: The client is aware of 1 parts, but the server has sent data for the 2 part!
[13:57:55] [main/INFO]: [STDERR]: 	at alexiil.mc.lib.multipart.impl.PartContainer$1.readContext(PartContainer.java:132)
[13:57:55] [main/INFO]: [STDERR]: 	at alexiil.mc.lib.multipart.impl.PartContainer$1.readContext(PartContainer.java:106)
[13:57:55] [main/INFO]: [STDERR]: 	at alexiil.mc.lib.net.ParentNetIdDuel.readContextCall(ParentNetIdDuel.java:74)
[13:57:55] [main/INFO]: [STDERR]: 	at alexiil.mc.lib.net.NetIdTyped.receive(NetIdTyped.java:29)
[13:57:55] [main/INFO]: [STDERR]: 	at alexiil.mc.lib.net.InternalMsgUtil.onReceive(InternalMsgUtil.java:259)
[13:57:55] [main/INFO]: [STDERR]: 	... 16 more

```

**Comment by Skywrath-Mage** [comment]
After re-install of the server and importing the maps file, no profile, no config. 
Start to work again.
